In [ ]:
import pandas as pd

path = "../datasets/greengrid_v2_2/raw_data/"

In [116]:
def cat_flag(data: pd.DataFrame):
    """Flagging inconsistency in categorical data"""
    columns = list(data.columns)
    for column in columns:
        if data[column].dtypes == "object":
            a = list(
                    set(
                        [i.upper().strip() for i in list(data[column].unique().astype(str))]
                        )
                )
            b = list(data[column].unique())
            if len(a) == len(b):
                print(column, "->", "Consistent")
            else:
                print(column, "->", "Inconsistent")

### Asset

In [96]:
assets = path + "asset_registry_raw.csv"

df_assets = pd.read_csv(assets)

df_assets

,asset_id,asset_name,technology,region,grid_node,capacity_mw,commission_date,asset_status,source_system
0,SOL-N01,North Solar One,Solar PV,North,NORTH_A,180,2023-06-01,Operational,ASSET_REGISTRY
1,SOL-N02,North Solar Two,Solar PV,North,NORTH_A,140,2024-03-15,Operational,ASSET_REGISTRY
2,WND-N01,North Wind One,WIND,North,NORTH_B,220,2022-10-01,Operational,ASSET_REGISTRY
3,SOL-C01,Central Solar One,Solar PV,Central,CENTRAL_A,160,2023-01-10,Operational,ASSET_REGISTRY
4,SOL-C02,Central Solar Two,Solar PV,Central,CENTRAL_A,110,2024-07-01,Operational,ASSET_REGISTRY
5,WND-C01,Central Wind One,wind,central,CENTRAL_B,180,2022-05-20,Operational,ASSET_REGISTRY

In [118]:
cat_flag(df_assets)

asset_id -> Consistent
asset_name -> Consistent
technology -> Inconsistent
region -> Inconsistent
grid_node -> Consistent
commission_date -> Consistent
asset_status -> Consistent
source_system -> Consistent

Terdapat **Inkonsistensi** pada kolom `technology` dan `region`

In [102]:
df_assets.duplicated().sum()

np.int64(0)

In [103]:
df_assets.isnull().sum()

asset_id           0
asset_name         0
technology         0
region             0
grid_node          0
capacity_mw        0
commission_date    0
asset_status       0
source_system      0
dtype: int64

In [104]:
df_assets.dtypes

asset_id           object
asset_name         object
technology         object
region             object
grid_node          object
capacity_mw         int64
commission_date    object
asset_status       object
source_system      object
dtype: object

In [105]:
df_assets.describe()

       capacity_mw
count     6.000000
mean    165.000000
std      37.815341
min     110.000000
25%     145.000000
50%     170.000000
75%     180.000000
max     220.000000

## BESS

In [106]:
bess = path + "bess_operations_raw.csv"

df_bess = pd.read_csv(bess)

df_bess.head()

,timestamp,region,battery_power_capacity_mw,battery_energy_capacity_mwh,charge_mwh,discharge_mwh,source_system,record_status
0,2025-01-01 00:00:00,North,50,200,0.0,0.0,BESS_CONTROLLER,VALID
1,2025-01-01 00:00:00,Central,50,200,0.0,0.0,BESS_CONTROLLER,VALID
2,2025-01-01 01:00:00,North,50,200,0.0,0.0,BESS_CONTROLLER,VALID
3,2025-01-01 01:00:00,Central,50,200,0.0,0.0,BESS_CONTROLLER,VALID
4,2025-01-01 02:00:00,North,50,200,0.0,0.0,BESS_CONTROLLER,VALID

In [124]:
df_bess.dtypes

timestamp                       object
region                          object
battery_power_capacity_mw        int64
battery_energy_capacity_mwh      int64
charge_mwh                     float64
discharge_mwh                  float64
source_system                   object
record_status                   object
dtype: object

In [119]:
cat_flag(df_bess)

timestamp -> Consistent
region -> Inconsistent
source_system -> Consistent
record_status -> Consistent

Terdapat **Inkonsistensi** pada kolom `region`

In [109]:
df_bess.duplicated().sum()

np.int64(34)

In [110]:
df_bess.isnull().sum()

timestamp                       0
region                          0
battery_power_capacity_mw       0
battery_energy_capacity_mwh     0
charge_mwh                     52
discharge_mwh                   0
source_system                   0
record_status                   0
dtype: int64

In [112]:
df_bess.describe()

,battery_power_capacity_mw,battery_energy_capacity_mwh,charge_mwh,discharge_mwh
count,17555.0,17555.0,17503.000000,17555.000000
mean,50.0,200.0,2.767607,2.219812
std,0.0,0.0,18.095557,8.585359
min,50.0,200.0,-10.000000,0.000000
25%,50.0,200.0,0.000000,0.000000
50%,50.0,200.0,0.000000,0.000000
75%,50.0,200.0,0.000000,0.000000
max,50.0,200.0,999.000000,37.500000

Terdapat **outlier** pada kolom `charge_mwh`

### Dispatch

In [113]:
dispatch = path + "dispatch_curtailment_log_raw.csv"

df_dispatch = pd.read_csv(dispatch)

df_dispatch.head()

,event_id,region,start_time,end_time,reason,operator_action,source_system,record_status
0,CE-00001,North,2025-01-11 12:00:00,2025-01-11 12:00:00,storage_constraint,Dispatch down renewable output,DISPATCH_LOG,VALID
1,CE-00002,North,2025-01-25 11:00:00,2025-01-25 13:00:00,storage_constraint,Dispatch down renewable output,DISPATCH_LOG,VALID
2,CE-00003,North,2025-02-01 11:00:00,2025-02-01 11:00:00,storage_constraint,Dispatch down renewable output,DISPATCH_LOG,VALID
3,CE-00004,North,2025-02-02 10:00:00,2025-02-02 10:00:00,storage_constraint,Dispatch down renewable output,DISPATCH_LOG,VALID
4,CE-00005,North,2025-02-02 14:00:00,2025-02-02 14:00:00,storage_constraint,Dispatch down renewable output,DISPATCH_LOG,VALID

In [120]:
df_dispatch.dtypes

event_id           object
region             object
start_time         object
end_time           object
reason             object
operator_action    object
source_system      object
record_status      object
dtype: object

In [121]:
cat_flag(df_dispatch)

event_id -> Consistent
region -> Consistent
start_time -> Consistent
end_time -> Consistent
reason -> Inconsistent
operator_action -> Consistent
source_system -> Consistent
record_status -> Consistent

In [126]:
df_dispatch.duplicated().sum()

np.int64(3)

In [127]:
df_dispatch.isnull().sum()

event_id           0
region             0
start_time         0
end_time           0
reason             4
operator_action    0
source_system      0
record_status      0
dtype: int64

In [129]:
df_dispatch.describe()

,event_id,region,start_time,end_time,reason,operator_action,source_system,record_status
count,306,306,306,306,302,306,306,306
unique,303,1,303,303,7,1,1,1
top,CE-00112,North,2025-05-25 09:00:00,2025-05-25 10:00:00,grid_constraint,Dispatch down renewable output,DISPATCH_LOG,VALID
freq,2,306,2,2,227,306,306,306

### EMS

In [137]:
ems = path + "ems_operations_raw.csv"
df_ems = pd.read_csv(ems)

df_ems.head()

,timestamp,total_demand_mwh,north_export_limit_mw,central_export_limit_mw,source_system,demand_unit,record_status
0,01/01/2025 00:00,269.595543,80.0,220.0,EMS,MWh,VALID
1,2025-01-01 01:00:00,304.452778,80.0,220.0,EMS,MWh,VALID
2,2025-01-01 02:00:00,285.878869,80.0,220.0,EMS,MWh,VALID
3,2025-01-01 03:00:00,299.750572,80.0,220.0,EMS,MWh,VALID
4,2025-01-01 04:00:00,321.041077,80.0,220.0,EMS,MWh,VALID

In [138]:
df_ems.dtypes

timestamp                   object
total_demand_mwh           float64
north_export_limit_mw      float64
central_export_limit_mw    float64
source_system               object
demand_unit                 object
record_status               object
dtype: object

In [139]:
cat_flag(df_ems)

timestamp -> Consistent
source_system -> Consistent
demand_unit -> Consistent
record_status -> Consistent

In [140]:
df_ems.duplicated().sum()

np.int64(17)

In [141]:
df_ems.isnull().sum()

timestamp                   0
total_demand_mwh           17
north_export_limit_mw       0
central_export_limit_mw     0
source_system               0
demand_unit                 0
record_status               0
dtype: int64

In [143]:
df_ems.describe()

       total_demand_mwh  north_export_limit_mw  central_export_limit_mw
count       8760.000000            8777.000000              8777.000000
mean         366.821448              77.203145               219.507713
std           64.732479               6.928185                 4.789410
min          201.609089              43.200000               158.400000
25%          317.914486              80.000000               220.000000
50%          366.182486              80.000000               220.000000
75%          411.871106              80.000000               220.000000
max          551.613558              80.000000               220.000000

### Market Price

In [144]:
market_price = path + "market_price_raw.csv"
df_market_price = pd.read_csv(market_price)

df_market_price.head()

             timestamp  market_price_usd_per_mwh source_system record_status
0  2025-01-01 00:00:00                     52.97   MARKET_FEED         VALID
1  2025-01-01 01:00:00                     55.24   MARKET_FEED         VALID
2  2025-01-01 02:00:00                     63.02   MARKET_FEED         VALID
3  2025-01-01 03:00:00                     54.80   MARKET_FEED         VALID
4  2025-01-01 04:00:00                     63.04   MARKET_FEED         VALID

In [145]:
df_market_price.dtypes

timestamp                    object
market_price_usd_per_mwh    float64
source_system                object
record_status                object
dtype: object

In [146]:
cat_flag(df_market_price)

timestamp -> Consistent
source_system -> Consistent
record_status -> Consistent

In [147]:
df_market_price.duplicated().sum()

np.int64(16)

In [148]:
df_market_price.isnull().sum()

timestamp                    0
market_price_usd_per_mwh    17
source_system                0
record_status                0
dtype: int64

In [150]:
df_market_price.describe()

       market_price_usd_per_mwh
count               8760.000000
mean                  67.831773
std                   11.072428
min                  -14.750000
25%                   61.640000
50%                   68.400000
75%                   75.010000
max                   95.080000

Terdapat **outlier** pada kolom `market_price_usd_per_mwh`

### SCADA

In [130]:
scada = path + "scada_generation_raw.csv"

df_scada = pd.read_csv(scada)

df_scada.head()

,timestamp,asset_id,capacity_mw,availability_pct,source_system,reading_status
0,2025-01-01 00:00:00,SOL-N01,180,98.954049,SCADA,VALID
1,2025-01-01 01:00:00,SOL-N01,180,98.271865,SCADA,VALID
2,2025-01-01 02:00:00,SOL-N01,180,99.840617,SCADA,VALID
3,2025-01-01 03:00:00,SOL-N01,180,99.483940,SCADA,VALID
4,2025-01-01 04:00:00,SOL-N01,180,98.098109,SCADA,VALID

In [131]:
df_scada.dtypes

timestamp            object
asset_id             object
capacity_mw           int64
availability_pct    float64
source_system        object
reading_status       object
dtype: object

In [132]:
cat_flag(df_scada)

timestamp -> Consistent
asset_id -> Consistent
source_system -> Consistent
reading_status -> Consistent

In [133]:
df_scada.duplicated().sum()

np.int64(103)

In [134]:
df_scada.isnull().sum()

timestamp             0
asset_id              0
capacity_mw           0
availability_pct    105
source_system         0
reading_status        0
dtype: int64

In [136]:
df_scada.describe()

        capacity_mw  availability_pct
count  52665.000000      52560.000000
mean     165.002563         97.869907
std       34.520825          7.019795
min      110.000000         -5.000000
25%      140.000000         97.938447
50%      180.000000         98.480544
75%      180.000000         99.029490
max      220.000000        150.000000

Terdapat **outlier** pada kolom `availability_pct`

### Weather

In [151]:
weather = path + "weather_station_raw.csv"
df_weather = pd.read_csv(weather)

df_weather.head()

,timestamp,station_id,solar_irradiance_index,wind_speed_mps,temperature_c,source_system,record_status
0,2025-01-01 00:00:00,WX-MASTER,0.0,8.795,28.11,WEATHER_STATION,VALID
1,2025-01-01 01:00:00,WX-MASTER,0.0,6.695,27.40,WEATHER_STATION,VALID
2,2025-01-01 02:00:00,WX-MASTER,0.0,7.087,25.98,WEATHER_STATION,VALID
3,2025-01-01 03:00:00,WX-MASTER,0.0,6.664,24.87,WEATHER_STATION,VALID
4,2025-01-01 04:00:00,WX-MASTER,0.0,7.283,24.71,WEATHER_STATION,VALID

In [152]:
df_weather.dtypes

timestamp                  object
station_id                 object
solar_irradiance_index    float64
wind_speed_mps            float64
temperature_c             float64
source_system              object
record_status              object
dtype: object

In [153]:
cat_flag(df_weather)

timestamp -> Consistent
station_id -> Consistent
source_system -> Consistent
record_status -> Consistent

In [154]:
df_weather.duplicated().sum()

np.int64(17)

In [156]:
df_weather.isnull().sum()

timestamp                  0
station_id                 0
solar_irradiance_index     0
wind_speed_mps            35
temperature_c              0
source_system              0
record_status              0
dtype: int64

In [158]:
df_weather.describe()

       solar_irradiance_index  wind_speed_mps  temperature_c
count             8777.000000     8742.000000    8777.000000
mean                 0.276228        7.025295      26.972137
std                  0.337455        2.000557       3.035083
min                  0.000000       -2.000000      17.740000
25%                  0.000000        5.815000      24.650000
50%                  0.000000        7.010000      26.960000
75%                  0.603000        8.205000      29.260000
max                  1.049000       60.000000      35.580000

Terdapat **invalid value** pada kolom `solar_irradiance_index` dan `wind_speed_mps`